/*
 * Backup and DR Service: Management Console API Spec
 *
 * This document defines the API for the Global Manager. All communication is done over HTTPS with UTF-8 encoding. JSON is the only supported format for both request and response payloads. <p></p>Please read <a href=\"https://cloud.google.com/backup-disaster-recovery/docs/api/RestAPIGeneralConcepts.pdf\">Management Console API General concept</a><p></p>To login, use the /session POST API below.<br></br>Then copy the resulting session_id from the output and click on the Authorize button on the top right. Paste the string \"Actifio \" followed by the session id into the form and click Authorize.<p></p>Login is not necessary for reading the rest of this API document. However, login will allow you to try the APIs out within this page.
 *
 * API version: V11.0.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type InlineResponse200 struct {
	Date time.Time `json:"date,omitempty"`
	LastModified time.Time `json:"lastModified,omitempty"`
	Headers map[string][]interface{} `json:"headers,omitempty"`
	Status int32 `json:"status,omitempty"`
	MediaType *InlineResponse200MediaType `json:"mediaType,omitempty"`
	Metadata map[string][]interface{} `json:"metadata,omitempty"`
	Entity *interface{} `json:"entity,omitempty"`
	AllowedMethods []string `json:"allowedMethods,omitempty"`
	EntityTag *InlineResponse200EntityTag `json:"entityTag,omitempty"`
	Links []InlineResponse200Links `json:"links,omitempty"`
	StatusInfo *InlineResponse200StatusInfo `json:"statusInfo,omitempty"`
	Cookies map[string]InlineResponse200Cookies `json:"cookies,omitempty"`
	StringHeaders map[string][]string `json:"stringHeaders,omitempty"`
	Length int32 `json:"length,omitempty"`
	Location string `json:"location,omitempty"`
	Language *InlineResponse200Language `json:"language,omitempty"`
}
