/*
 * Backup and DR Service: Management Console API Spec
 *
 * This document defines the API for the Global Manager. All communication is done over HTTPS with UTF-8 encoding. JSON is the only supported format for both request and response payloads. <p></p>Please read <a href=\"https://cloud.google.com/backup-disaster-recovery/docs/api/RestAPIGeneralConcepts.pdf\">Management Console API General concept</a><p></p>To login, use the /session POST API below.<br></br>Then copy the resulting session_id from the output and click on the Authorize button on the top right. Paste the string \"Actifio \" followed by the session id into the form and click Authorize.<p></p>Login is not necessary for reading the rest of this API document. However, login will allow you to try the APIs out within this page.
 *
 * API version: V11.0.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Backup Rest Object
type BackupRest struct {
	Mountmigrateflag bool `json:"mountmigrateflag,omitempty"`
	Eligiblestoragetypes string `json:"eligiblestoragetypes,omitempty"`
	Targetstoragetype string `json:"targetstoragetype,omitempty"`
	Migrationstate string `json:"migrationstate,omitempty"`
	Datafilemovestarted bool `json:"datafilemovestarted,omitempty"`
	// source to target storage mapping
	Migratemapping string `json:"migratemapping,omitempty"`
	IsSourceAppFromMountMigrateRestore bool `json:"isSourceAppFromMountMigrateRestore,omitempty"`
	Backedupdbnames string `json:"backedupdbnames,omitempty"`
	Cloudcredential *CloudCredentialRest `json:"cloudcredential,omitempty"`
	Releaselogs bool `json:"releaselogs,omitempty"`
	Retainlogs bool `json:"retainlogs,omitempty"`
	Label string `json:"label,omitempty"`
	Version string `json:"version,omitempty"`
	Flags string `json:"flags,omitempty"`
	Jobclasscode int32 `json:"jobclasscode,omitempty"`
	Zone string `json:"zone,omitempty"`
	Expiration int64 `json:"expiration,omitempty"`
	Modifydate int64 `json:"modifydate,omitempty"`
	Status string `json:"status,omitempty"`
	Srcid string `json:"srcid,omitempty"`
	Clusterid string `json:"clusterid,omitempty"`
	Appname string `json:"appname,omitempty"`
	Application *ApplicationRest `json:"application,omitempty"`
	Isasm bool `json:"isasm,omitempty"`
	Apptype string `json:"apptype,omitempty"`
	Snapshottype string `json:"snapshottype,omitempty"`
	Jobclass string `json:"jobclass,omitempty"`
	Consumedsize int64 `json:"consumedsize,omitempty"`
	Catalogstate string `json:"catalogstate,omitempty"`
	Backupname string `json:"backupname,omitempty"`
	Sourceuds string `json:"sourceuds,omitempty"`
	Originatinguds string `json:"originatinguds,omitempty"`
	Targetuds string `json:"targetuds,omitempty"`
	Appclass string `json:"appclass,omitempty"`
	Cluster *ClusterRest `json:"cluster,omitempty"`
	Diskpool *DiskPoolRest `json:"diskpool,omitempty"`
	Transport string `json:"transport,omitempty"`
	Sensitivity int32 `json:"sensitivity,omitempty"`
	Multiregion string `json:"multiregion,omitempty"`
	Vaultowner bool `json:"vaultowner,omitempty"`
	Mountedhost []HostRest `json:"mountedhost,omitempty"`
	Uniquehostname string `json:"uniquehostname,omitempty"`
	Modifiedbytes string `json:"modifiedbytes,omitempty"`
	Hasdependency bool `json:"hasdependency,omitempty"`
	Originalbackupid string `json:"originalbackupid,omitempty"`
	Backupdate int64 `json:"backupdate,omitempty"`
	Immutabilitydate int64 `json:"immutabilitydate,omitempty"`
	Consistencydate int64 `json:"consistencydate,omitempty"`
	Mappedhost string `json:"mappedhost,omitempty"`
	Virtualsize string `json:"virtualsize,omitempty"`
	Slpname string `json:"slpname,omitempty"`
	Sltname string `json:"sltname,omitempty"`
	Policyname string `json:"policyname,omitempty"`
	Characteristic string `json:"characteristic,omitempty"`
	Sourceimage *BackupRest `json:"sourceimage,omitempty"`
	Snapshotlocation string `json:"snapshotlocation,omitempty"`
	Endpit int64 `json:"endpit,omitempty"`
	Beginpit int64 `json:"beginpit,omitempty"`
	Racnodelist []string `json:"racnodelist,omitempty"`
	Restorableobjects []RestorableRest `json:"restorableobjects,omitempty"`
	Powerfactor int32 `json:"powerfactor,omitempty"`
	Provisioningoptions []KeyValueRest `json:"provisioningoptions,omitempty"`
	Vmname string `json:"vmname,omitempty"`
	Copies []BackupRest `json:"copies,omitempty"`
	Hasmountedmap bool `json:"hasmountedmap,omitempty"`
	Childapp *ApplicationRest `json:"childapp,omitempty"`
	Restorelock string `json:"restorelock,omitempty"`
	Mountcapacity int64 `json:"mountcapacity,omitempty"`
	Nvolumes string `json:"nvolumes,omitempty"`
	Originalbackup *BackupRest `json:"originalbackup,omitempty"`
	Dnsname string `json:"dnsname,omitempty"`
	Vmpath string `json:"vmpath,omitempty"`
	Esxhost string `json:"esxhost,omitempty"`
	Backuplock string `json:"backuplock,omitempty"`
	Mountedmountpoint string `json:"mountedmountpoint,omitempty"`
	Consistencymode string `json:"consistencymode,omitempty"`
	Mountedvdisk string `json:"mountedvdisk,omitempty"`
	Sourcemountpoint string `json:"sourcemountpoint,omitempty"`
	FlagsText []string `json:"flags_text,omitempty"`
	Expirytries string `json:"expirytries,omitempty"`
	Logsequences []LogSequenceRest `json:"logsequences,omitempty"`
	Hosttimezone string `json:"hosttimezone,omitempty"`
	Hostisdst bool `json:"hostisdst,omitempty"`
	Asmswitchcapable bool `json:"asmswitchcapable,omitempty"`
	Incarnation string `json:"incarnation,omitempty"`
	Hananodelist []string `json:"hananodelist,omitempty"`
	ApplicationAllocatedSize int64 `json:"application_allocated_size,omitempty"`
	Exportvolume []ExportVolumeInfoRest `json:"exportvolume,omitempty"`
	Sourcediskpool *DiskPoolRest `json:"sourcediskpool,omitempty"`
	Clonemigrateeligible bool `json:"clonemigrateeligible,omitempty"`
	MigrateFrequency int32 `json:"migrate-frequency,omitempty"`
	MigrateCopythreadcount int32 `json:"migrate-copythreadcount,omitempty"`
	MigrateConfigured bool `json:"migrate-configured,omitempty"`
	Yaml string `json:"yaml,omitempty"`
	Yamlavailable bool `json:"yamlavailable,omitempty"`
	Allowedips []string `json:"allowedips,omitempty"`
	Volgroupname string `json:"volgroupname,omitempty"`
	Name string `json:"name,omitempty"`
	Host *HostRest `json:"host,omitempty"`
	// URL to access this object
	Href string `json:"href,omitempty"`
	// When this object was last synced from appliances (UNIX Epoch time in microseconds). It does not apply to local resources.
	Syncdate int64 `json:"syncdate,omitempty"`
	// Optional flag to indicate if the information is out-of-date due to communication problems with appliances. It does not apply to local resources.
	Stale bool `json:"stale,omitempty"`
	// Unique ID for this object
	Id string `json:"id,omitempty"`
}
