/*
Backup and DR Service: Management Console API Spec

This document defines the API for the Global Manager. All communication is done over HTTPS with UTF-8 encoding. JSON is the only supported format for both request and response payloads. <p></p>Please read <a href=\"https://cloud.google.com/backup-disaster-recovery/docs/api/RestAPIGeneralConcepts.pdf\">Management Console API General concept</a><p></p>To login, use the /session POST API below.<br></br>Then copy the resulting session_id from the output and click on the Authorize button on the top right. Paste the string \"Actifio \" followed by the session id into the form and click Authorize.<p></p>Login is not necessary for reading the rest of this API document. However, login will allow you to try the APIs out within this page.

API version: V11.0.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SystemStateOptionRest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SystemStateOptionRest{}

// SystemStateOptionRest struct for SystemStateOptionRest
type SystemStateOptionRest struct {
	Name *string `json:"name,omitempty"`
	Value *string `json:"value,omitempty"`
	Structurevalue []SystemStateOptionRest `json:"structurevalue,omitempty"`
	// Unique ID for this object
	Id *string `json:"id,omitempty"`
	// URL to access this object
	Href *string `json:"href,omitempty"`
	// When this object was last synced from appliances (UNIX Epoch time in microseconds). It does not apply to local resources.
	Syncdate *int64 `json:"syncdate,omitempty"`
	// Optional flag to indicate if the information is out-of-date due to communication problems with appliances. It does not apply to local resources.
	Stale *bool `json:"stale,omitempty"`
}

// NewSystemStateOptionRest instantiates a new SystemStateOptionRest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSystemStateOptionRest() *SystemStateOptionRest {
	this := SystemStateOptionRest{}
	return &this
}

// NewSystemStateOptionRestWithDefaults instantiates a new SystemStateOptionRest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSystemStateOptionRestWithDefaults() *SystemStateOptionRest {
	this := SystemStateOptionRest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SystemStateOptionRest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemStateOptionRest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SystemStateOptionRest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SystemStateOptionRest) SetName(v string) {
	o.Name = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *SystemStateOptionRest) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemStateOptionRest) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *SystemStateOptionRest) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *SystemStateOptionRest) SetValue(v string) {
	o.Value = &v
}

// GetStructurevalue returns the Structurevalue field value if set, zero value otherwise.
func (o *SystemStateOptionRest) GetStructurevalue() []SystemStateOptionRest {
	if o == nil || IsNil(o.Structurevalue) {
		var ret []SystemStateOptionRest
		return ret
	}
	return o.Structurevalue
}

// GetStructurevalueOk returns a tuple with the Structurevalue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemStateOptionRest) GetStructurevalueOk() ([]SystemStateOptionRest, bool) {
	if o == nil || IsNil(o.Structurevalue) {
		return nil, false
	}
	return o.Structurevalue, true
}

// HasStructurevalue returns a boolean if a field has been set.
func (o *SystemStateOptionRest) HasStructurevalue() bool {
	if o != nil && !IsNil(o.Structurevalue) {
		return true
	}

	return false
}

// SetStructurevalue gets a reference to the given []SystemStateOptionRest and assigns it to the Structurevalue field.
func (o *SystemStateOptionRest) SetStructurevalue(v []SystemStateOptionRest) {
	o.Structurevalue = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *SystemStateOptionRest) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemStateOptionRest) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SystemStateOptionRest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *SystemStateOptionRest) SetId(v string) {
	o.Id = &v
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *SystemStateOptionRest) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemStateOptionRest) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *SystemStateOptionRest) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *SystemStateOptionRest) SetHref(v string) {
	o.Href = &v
}

// GetSyncdate returns the Syncdate field value if set, zero value otherwise.
func (o *SystemStateOptionRest) GetSyncdate() int64 {
	if o == nil || IsNil(o.Syncdate) {
		var ret int64
		return ret
	}
	return *o.Syncdate
}

// GetSyncdateOk returns a tuple with the Syncdate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemStateOptionRest) GetSyncdateOk() (*int64, bool) {
	if o == nil || IsNil(o.Syncdate) {
		return nil, false
	}
	return o.Syncdate, true
}

// HasSyncdate returns a boolean if a field has been set.
func (o *SystemStateOptionRest) HasSyncdate() bool {
	if o != nil && !IsNil(o.Syncdate) {
		return true
	}

	return false
}

// SetSyncdate gets a reference to the given int64 and assigns it to the Syncdate field.
func (o *SystemStateOptionRest) SetSyncdate(v int64) {
	o.Syncdate = &v
}

// GetStale returns the Stale field value if set, zero value otherwise.
func (o *SystemStateOptionRest) GetStale() bool {
	if o == nil || IsNil(o.Stale) {
		var ret bool
		return ret
	}
	return *o.Stale
}

// GetStaleOk returns a tuple with the Stale field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemStateOptionRest) GetStaleOk() (*bool, bool) {
	if o == nil || IsNil(o.Stale) {
		return nil, false
	}
	return o.Stale, true
}

// HasStale returns a boolean if a field has been set.
func (o *SystemStateOptionRest) HasStale() bool {
	if o != nil && !IsNil(o.Stale) {
		return true
	}

	return false
}

// SetStale gets a reference to the given bool and assigns it to the Stale field.
func (o *SystemStateOptionRest) SetStale(v bool) {
	o.Stale = &v
}

func (o SystemStateOptionRest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SystemStateOptionRest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	if !IsNil(o.Structurevalue) {
		toSerialize["structurevalue"] = o.Structurevalue
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}
	if !IsNil(o.Syncdate) {
		toSerialize["syncdate"] = o.Syncdate
	}
	if !IsNil(o.Stale) {
		toSerialize["stale"] = o.Stale
	}
	return toSerialize, nil
}

type NullableSystemStateOptionRest struct {
	value *SystemStateOptionRest
	isSet bool
}

func (v NullableSystemStateOptionRest) Get() *SystemStateOptionRest {
	return v.value
}

func (v *NullableSystemStateOptionRest) Set(val *SystemStateOptionRest) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemStateOptionRest) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemStateOptionRest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemStateOptionRest(val *SystemStateOptionRest) *NullableSystemStateOptionRest {
	return &NullableSystemStateOptionRest{value: val, isSet: true}
}

func (v NullableSystemStateOptionRest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemStateOptionRest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


