/*
Backup and DR Service: Management Console API Spec

This document defines the API for the Global Manager. All communication is done over HTTPS with UTF-8 encoding. JSON is the only supported format for both request and response payloads. <p></p>Please read <a href=\"https://cloud.google.com/backup-disaster-recovery/docs/api/RestAPIGeneralConcepts.pdf\">Management Console API General concept</a><p></p>To login, use the /session POST API below.<br></br>Then copy the resulting session_id from the output and click on the Authorize button on the top right. Paste the string \"Actifio \" followed by the session id into the form and click Authorize.<p></p>Login is not necessary for reading the rest of this API document. However, login will allow you to try the APIs out within this page.

API version: V11.0.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the JSONArray type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JSONArray{}

// JSONArray struct for JSONArray
type JSONArray struct {
	Empty *bool `json:"empty,omitempty"`
}

// NewJSONArray instantiates a new JSONArray object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJSONArray() *JSONArray {
	this := JSONArray{}
	return &this
}

// NewJSONArrayWithDefaults instantiates a new JSONArray object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJSONArrayWithDefaults() *JSONArray {
	this := JSONArray{}
	return &this
}

// GetEmpty returns the Empty field value if set, zero value otherwise.
func (o *JSONArray) GetEmpty() bool {
	if o == nil || IsNil(o.Empty) {
		var ret bool
		return ret
	}
	return *o.Empty
}

// GetEmptyOk returns a tuple with the Empty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JSONArray) GetEmptyOk() (*bool, bool) {
	if o == nil || IsNil(o.Empty) {
		return nil, false
	}
	return o.Empty, true
}

// HasEmpty returns a boolean if a field has been set.
func (o *JSONArray) HasEmpty() bool {
	if o != nil && !IsNil(o.Empty) {
		return true
	}

	return false
}

// SetEmpty gets a reference to the given bool and assigns it to the Empty field.
func (o *JSONArray) SetEmpty(v bool) {
	o.Empty = &v
}

func (o JSONArray) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JSONArray) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Empty) {
		toSerialize["empty"] = o.Empty
	}
	return toSerialize, nil
}

type NullableJSONArray struct {
	value *JSONArray
	isSet bool
}

func (v NullableJSONArray) Get() *JSONArray {
	return v.value
}

func (v *NullableJSONArray) Set(val *JSONArray) {
	v.value = val
	v.isSet = true
}

func (v NullableJSONArray) IsSet() bool {
	return v.isSet
}

func (v *NullableJSONArray) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJSONArray(val *JSONArray) *NullableJSONArray {
	return &NullableJSONArray{value: val, isSet: true}
}

func (v NullableJSONArray) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJSONArray) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


